### ISSUE TITLE
Feature extraction from images (task 1)

### ISSUE THREAD

**Issue by hermesvf** [MCV-2019-M1-Project/Team1#5]
- [x] Read image from disk
- [x] Compute histogram
- [x] Color normalization (test different color spaces (HSV, Lab, others), and normalize for lightness)
- [ ] Process histogram (convolute, smooth, multi-resolution)
- [x] Save characteristics file to disk (extension to be determined)

**Comment by rbagan** [comment]
Missing apply several kind of histograms methods, openning a new branch for that
